// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://govjnfbgbdlmdycduccc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdmpuZmJnYmRsbWR5Y2R1Y2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODA5ODcsImV4cCI6MjA2MjM1Njk4N30.kV4aORx-pItzXMB7q5cmST7Cx78-U2ixaEz-Y1JiexA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);